# Generated by Django 5.0.4 on 2024-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='name',
            field=models.CharField(default='code', max_length=50),
            preserve_default=False,
        ),
    ]
