# Generated by Django 5.0.4 on 2024-07-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0004_alter_timer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 8, 17, 34, 53, 72450)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 8, 16, 47, 53, 72450)),
        ),
    ]
