# Generated by Django 5.0.4 on 2024-07-08 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0007_alter_timer_end_time_alter_timer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 8, 17, 51, 54, 768187)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 8, 17, 6, 54, 768187)),
        ),
    ]
