# Generated by Django 5.0.4 on 2024-07-08 16:33

import timertask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timertask', '0009_alter_timer_end_time_alter_timer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_time',
            field=models.TimeField(default=timertask.models.default_end_time),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.TimeField(default=timertask.models.default_start_time),
        ),
    ]
